---
- name: Setup Web Server
  hosts: all
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Copy index.html from template
      template:
        src: index-facts.html.j2
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
