---
- name: Setup
  hosts: all
  gather_facts: false

  tasks:
    - name: 'Set Root Password to "asdfasdf"'
      user:
        name: root
        password: '{{ "asdfasdf" | password_hash("sha512") }}'
    - name: Allow Root Login
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: PermitRootLogin
        line: PermitRootLogin yes
      notify:
        - restart sshd
    - name: Allow Password Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regex: PasswordAuthentication
        line: PasswordAuthentication yes
      notify:
        - restart sshd
  handlers:
    - name: restart sshd
      service:
        name: sshd
        state: restarted
